### ISSUE TITLE
When checking limit, plugin first using the TYPE then SUBTYPE. 

### ISSUE THREAD

**Issue by dorimanx** [N1Ran/BlockLimiter#23] opened 2020-04-09 12:54 UTC
Hi,

When adding custom block to limit, in my case serverlink (jumpgates) to limit and setting 0 limit so players will not add it.
It's preventing them to place beacons! as subtype serverlink is TYPE beacon!.
But i didnt set any limit for beacons!
only subtype serverlink it's same in pair name.
So problem is that plugin ignore direct written limit by subtype or pairname, and goes for TYPE and lock all blocks with same TYPE.
This true for all weapons!
What i am doing wrong? is there a special way to set limit?
Like:
SUBTYPY/NAME
OR
pairname/NAME

I just added pairnames or subtypes in Block Type window.

Thanks.

**Comment by N1Ran** [comment] 2020-04-09 13:17
Use subtypeID for unique blocks.  Pairnames can be shared but subtypeID is unique for each block.  And to make limit for any block that share typeId with any other block, you'd have to use a list of subtypeIDs to prevent that limit being triggered

**Comment by dorimanx** [comment] 2020-04-09 13:33
ok, i will switch to use only subtypes, right now most of limits are pairnames as vanila.
One more issue that i have seen, i have set weapon block with limit 4 based on grid limit.
now 2 players placed 4 blocks each on there grid, then connected both grids via connector, and limiter deleted all 8 blocks...
so check was thinking that it's one grid, but why deleted all 8.. and not just 4?
Can you please check if it's connected grid then not activate punishment?

Thanks

**Comment by N1Ran** [comment] 2020-04-09 13:39
That shouldn't happen.  Punishment doesn't read subgrids.  Block placement handle is the only part where subgrids are calculated.  If you have a limit set for player/faction, that could be why.  Also, check vanilla limits if you have any active.

**Comment by dorimanx** [comment] 2020-04-09 13:47
Well limit set only for grid, and use vanila checkbox is off.
oh also one more thing!
When plugin is added to torch with guid it's always ENABLED.
if i uncheck the enable, reboot torch, and plugin is enabled again.
tried twice. same result, to disable plugin i had to remove the file from plugins folder.

**Comment by N1Ran** [comment] 2020-04-09 13:50
The enable issue will be an easy fix.  Will check and see if I can reproduce the connection issue.  Also, ask if they use merge block since that would make the grid count as one, but doesn't explain why 8 was deleted

**Comment by dorimanx** [comment] 2020-04-09 15:11
No, just connector in connected state, and all 8 blocks deleted... we had to restore lost components as they are rare..

**Comment by N1Ran** [comment] 2020-04-19 00:18
This should be fixed for last update.  Feel free to reopen if you're still experiencing the problem

**Closed by N1Ran** 2020-04-19 00:18 UTC
Labels: Help
